SELECT ?entity ?name ?artistName WHERE{
    ?entity rdf:type muser:Album;
            muser:name ?name;
            muser:releasedBy ?artist.
    ?artist muser:name ?artistName
    FILTER NOT EXISTS{
        ?entity muser:idSpotify ?idSpotify.
    }
}