select DISTINCT ?entity ?name ?imageURL ?date ?performer ?performerName  where {
    ?album rdf:type ?type;
           muser:hasMusicalGenre ?genreOfAlbum;
           muser:releaseDate     ?dateOfAlbum .
    ?entity rdf:type ?type;
            muser:name ?name;
            muser:hasMusicalGenre ?genre;
            muser:releaseDate ?date;
            muser:releasedBy ?performer.
    ?performer muser:name ?performerName.
    OPTIONAL{
        ?performer muser:imageURL ?performerImageURL
    }
    OPTIONAL {
        ?entity muser:imageURL ?imageURL
    }
            
    FILTER(?type=muser:Album)            
    FILTER(?album = {{=it.id}} )
    FILTER(?entity != ?album)
    FILTER((STR(YEAR(?dateOfAlbum))=(STR(YEAR(?date)))))
    FILTER(?genreOfAlbum=?genre)
} limit 100