SELECT DISTINCT ?entity ?name ?imageURL where { 
	?entity muser:hasMusicalGenre ?artistGenre.
    ?artistGenre muser:embracedBy ?relatedArtist.
    ?entity rdf:type muser:MusicalArtist.
    ?entity muser:name ?name;
            muser:imageURL ?imageURL.
    
    
    FILTER (?entity = muser:{{=it.artist}})
  	# FILTER (?entity != muser:{{=it.artist}})
} limit 100 
