SELECT ?entity ?name ?imageURL WHERE{
    ?entity rdf:type ?type;
            muser:name ?name;
            muser:imageURL ?imageURL.
    
    FILTER(?type={{=it.type}})
    FILTER(REGEX(?name,"^{{=it.name}}","i"))
}