select DISTINCT ?entity ?name ?imageURL ?performer ?performerName ?performerImageURL where {
    ?song rdf:type muser:Song;
          muser:performedBy ?performer.
    ?performer muser:performs ?entity;
               muser:name ?performerName;
               muser:imageURL ?performerImageURL.
    ?entity muser:name ?name;
            muser:imageURL ?imageURL.
    FILTER(?song = {{=it.song}})    
    FILTER(?entity != ?song)
} ORDER BY RAND() LIMIT 20