select * where {
     ?entity rdf:type ?type;
             muser:name ?name.

    OPTIONAL { ?entity muser:relatedMusicalGenre ?relatedGenres }            
    FILTER(?type=muser:MusicalGenre)            
    FILTER(?entity = {{=it.id}} )

} limit 100