select ?entity ?name ?imageURL where {
    ?artist rdf:type                        ?type;
            muser:relatedMusicalAgent       ?entity .
    ?entity rdf:type ?type;
             muser:name                     ?name ;
             muser:imageURL                 ?imageURL
    
    FILTER(?artist = {{=it.id}} )
    FILTER(?type in (muser:MusicalArtist))
} limit 20