select DISTINCT ?entity ?name ?releasedBy ?imageURL where {
     ?album rdf:type ?type;
             muser:releasedBy ?releasedBy.
    ?releasedBy muser:released ?entity .
    
    ?entity rdf:type ?type;
             muser:name ?name;
             muser:releasedBy ?releasedBy.
             
  OPTIONAL {?entity muser:imageURL ?imageURL}

    FILTER(?type=muser:Album)            
    FILTER(?album = {{=it.id}} )
    FILTER(?entity != ?album)


} limit 100