select  ?entity ?name ?inceptionDate ?performer ?performerName where {
    ?genre rdf:type ?type;
           muser:embracedBy ?entity.
    ?entity  rdf:type ?entityType;
             muser:name ?name ;
             muser:releaseDate ?inceptionDate;
             muser:performedBy ?performer.
    ?performer muser:name ?performerName    
    
    FILTER(?type=muser:MusicalGenre)         
    FILTER(?entityType=(muser:Album))
    FILTER(?genre = {{=it.id}} )
    FILTER((STR(YEAR(?inceptionDate))) > "{{=it.start_date}}" )

} limit 100