SELECT DISTINCT ?entity ?name ?imageURL  WHERE{
    ?artist muser:hasMusicalGenre ?genre.
    ?genre muser:embracedBy ?entity.
    ?entity muser:name ?name;
            rdf:type muser:MusicalAgent;
            muser:imageURL ?imageURL
    FILTER(?artist = {{=it.artist}} )
    FILTER(?entity != {{=it.artist}} )
} ORDER BY RAND() LIMIT 20