SELECT DISTINCT ?entity ?name ?imageURL WHERE{
    ?artist muser:released ?album.
    ?album muser:contains ?albumSong.
    ?albumSong muser:performedBy ?entity.
    ?entity muser:name ?name;
            muser:imageURL ?imageURL.
    FILTER(?artist = {{=it.artist}} )
    FILTER(?entity != {{=it.artist}} )
}ORDER BY RAND() LIMIT 20  