select * where { 
	?song rdf:type muser:Song;
       	  muser:performedBy ?performer.
   ?performer muser:performs ?entity.
   ?entity muser:name ?songName;
           muser:imageURL ?imageURL.
    
	FILTER(?song = {{=it.song}})    
    FILTER(?entity != ?song)
} limit 100 