SELECT ?entity ?name ?label ?sameWd WHERE {
    ?entity   rdf:type    ?type ;
              rdfs:label  ?label ;
              foaf:name   ?name ;
              owl:sameAs  ?sameWd .
    
    {{=it.song}} dbo:album  ?entity .
    ?entity      dbo:artist {{=it.artist}} .
    
    FILTER (?type IN (dbo:Album))
    FILTER (regex(str(?sameWd), "wikidata.org/entity"))
    FILTER (lang(?name) = "en") 
    FILTER (lang(?label) = "en")
} 