SELECT ?name ?releaseDate ?duration ?releasedBy ?sameWd WHERE {
  ${dbpInstance}    rdf:type        ?type ;
                    rdfs:label      ?name ;
                    # dbo:artist      ?releasedBy ;
                    dbo:releaseDate ?releaseDate ;
                    dbo:runtime     ?duration ;
                    owl:sameAs      ?sameWd .
  
  FILTER (?type IN (dbo:Album))
  FILTER (regex(str(?sameWd), "wikidata.org/entity"))
  FILTER (lang(?name) = "en") 
} 