SELECT ?entity ?name ?label ?releaseDate ?duration ?releasedBy ?sameWd WHERE {
    ?entity           rdf:type        ?type ;
                      rdfs:label      ?label ;
                      foaf:name       ?name ;
                      # dbo:artist      ?releasedBy ;
                      dbo:releaseDate ?releaseDate ;
                      dbo:runtime     ?duration ;
                      owl:sameAs      ?sameWd .
    
    FILTER (?entity = ${dbpInstance})
    FILTER (?type IN (dbo:Album))
    FILTER (regex(str(?sameWd), "wikidata.org/entity"))
    FILTER (lang(?name) = "en") 
    FILTER (lang(?label) = "en") 
} 