SELECT ?entity ?name ?label ?sameWd WHERE {
    ?entity         rdfs:label                  ?label ;
                    foaf:name                   ?name ;
                    rdf:type                    ?type ;
                    owl:sameAs                  ?sameWd ;
    			    dbo:associatedMusicalArtist ${dbpInstance} .
  
    FILTER (?type IN (dbo:MusicalArtist, dbo:Band))
    FILTER (regex(str(?sameWd), "http://www.wikidata.org/entity"))
    FILTER (lang(?name) = "en")
    FILTER (lang(?label) = "en")
}