SELECT  ?entity ?sameWd ?label ?name ?firstName ?lastName ?birthDate ?birthName ?gender ?musicalAgentOrigin ?inceptionDate ?retiringDate WHERE {
          ?entity   rdf:type                 ?type ;
                    rdfs:label               ?label ;
                    foaf:name			           ?name ;
                    dbo:abstract             ?aboutArtist .
        
          OPTIONAL { 
            ?entity ?originPredicate     ?musicalAgentOrigin .
            FILTER (?originPredicate IN (dbo:hometown, dbo:birthPlace))
  		    }
          OPTIONAL { ?entity dbo:activeYearsStartYear ?inceptionDate }
          OPTIONAL { ?entity dbo:activeYearsEndYear   ?retiringDate }
          OPTIONAL { ?entity dbo:birthName            ?birthName }
          OPTIONAL { ?entity foaf:givenName           ?firstName }
          OPTIONAL { ?entity foaf:surname             ?lastName }
          OPTIONAL { ?entity foaf:gender              ?gender }
          OPTIONAL { ?entity owl:sameAs               ?sameWd }
          
  		    FILTER (?entity = ${dbpInstance})
          FILTER (?type IN (dbo:MusicalArtist, dbo:Band))
          FILTER (regex(?sameWd, "wikidata.org/entity"))
          FILTER (lang(?label) = "en")
  		    FILTER (lang(?name) = "en")
          FILTER (lang(?aboutArtist) = "en")
}