SELECT ?entity ?sameWd ?label WHERE {
    ?entity         rdfs:label     ?label ;
                    rdf:type	   ?type ;
                    owl:sameAs     ?sameWd .

    ${dbpInstance}  dbo:bandMember  ?entity  .

    FILTER (?type IN (dbo:MusicalArtist))
  	FILTER (?type NOT IN (dbo:Band))
    FILTER (lang(?label) = "en")
    FILTER (regex(str(?sameWd), "wikidata.org/entity"))
}