SELECT  ?artist ?sameWd ?name ?firstName ?lastName ?birthName ?gender ?musicalAgentOrigin ?inceptionDate ?retiringDate WHERE {
          ?artist   rdf:type                 ?type ;
                    rdfs:label               ?name ;
                    dbo:abstract             ?aboutArtist .
        
          OPTIONAL { 
    			?artist ?originPredicate     ?musicalAgentOrigin .
    			FILTER (?originPredicate IN (dbo:hometown, dbo:birthPlace))
  		  }
          OPTIONAL { ?artist dbo:activeYearsStartYear ?inceptionDate }
          OPTIONAL { ?artist dbo:activeYearsEndYear   ?retiringDate }
          OPTIONAL { ?artist dbo:birthName            ?birthName }
          OPTIONAL { ?artist foaf:givenName           ?firstName }
          OPTIONAL { ?artist foaf:surname             ?lastName }
          OPTIONAL { ?artist foaf:gender              ?gender }
          OPTIONAL { ?artist owl:sameAs               ?sameWd }
          
          FILTER (?artist = ${dbpInstance})
          FILTER (?type IN (dbo:MusicalArtist, dbo:Band))
          FILTER (regex(?sameWd, "wikidata.org/entity"))
          FILTER (lang(?name) = "en")
          FILTER (lang(?aboutArtist) = "en")
}