SELECT ?relatedGenre ?name ?sameWd WHERE {
    ?relatedGenre       foaf:name 		?name ;
                        rdf:type		?type ;
                        owl:sameAs      ?sameWd .

    ${dbpInstance}      dbo:derivative  ?relatedGenre .

    FILTER (?type IN (dbo:MusicGenre))
    FILTER (regex(str(?sameWd), "wikidata.org/entity"))
    FILTER (lang(?name) = "en")
}