SELECT ?entity ?name ?label ?sameWd WHERE {
  ?entity     rdfs:label          ?label ;
            foaf:name           ?name ;
  		      rdf:type   		      ?type ;
    	      dbo:musicalArtist   ${dbpInstance} ;
      	    owl:sameAs          ?sameWd .
  
  FILTER (?type IN (dbo:MusicalWork))
  FILTER (?type NOT IN (dbo:Album))
  FILTER (regex(str(?sameWd), 'wikidata.org/entity'))
  FILTER (lang(?name) = 'en')
  FILTER (lang(?label) = 'en')
}